
server:
    port: 8081

spring:
    datasource:
        username: root
        #本地
        password: 12345678
        #云服务
        #password: 123456
        url: jdbc:mysql://localhost:3306/sm?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource

    thymeleaf:
        mode: HTML
        encoding: utf-8
        cache: false